services:
  web:
    build: .
    ports:
      - "8080:80"
    networks:
      - dockernet
    volumes:
      - ./:/usr/share/nginx/html

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
    networks:
      - dockernet

  admin:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - dockernet

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.5.1
    command:
      - --nginx.scrape-uri=http://web:80/stub_status
    ports:
      - "9113:9113"
    networks:
      - dockernet

networks:
  dockernet:
